resolver: https://raw.githubusercontent.com/metrix-ai/stack-snapshot/53/snapshot.yaml
extra-deps:
- {git: "https://github.com/nikita-volkov/most.hs", commit: "acfb227620f9b39922af49bbd02354c293c2fa9e"}
- {git: "https://github.com/metrix-ai/acquire", commit: "698b1cb819674b91eabd71e364d65e8e20d93fcc"}
